# Generated by Django 5.2.17 on 2026-08-25 13:58

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("fc", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="ISS-YYYY-NNNNN",
                        max_length=24,
                        unique=True,
                    ),
                ),
                (
                    "discovered_stage",
                    models.CharField(
                        choices=[
                            ("FABRICATION", "Fabrication"),
                            ("MANUAL_ASSEMBLY", "Manual Assembly"),
                            ("MACHINE_ASSEMBLY", "Machine Assembly / Soldering"),
                            ("QC", "QC"),
                            ("FIRMWARE", "Firmware"),
                            ("SENSOR_VALIDATION", "Sensor / Functional Validation"),
                            ("MECHANICAL_ASSEMBLY", "Mechanical Assembly"),
                            ("BENCH_TESTING", "Bench Testing"),
                            ("GROUND_TESTING", "Ground Testing"),
                            ("FINAL_VALIDATION", "Final Validation"),
                            ("MANAGER_APPROVAL", "Manager Approval"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("HARDWARE", "Hardware"),
                            ("FIRMWARE", "Firmware"),
                            ("SOFTWARE", "Software"),
                            ("MECHANICAL", "Mechanical"),
                            ("PROCESS", "Process"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        db_index=True,
                        default="UNKNOWN",
                        max_length=24,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("BLOCKER", "Blocker"),
                            ("MAJOR", "Major"),
                            ("MINOR", "Minor"),
                            ("COSMETIC", "Cosmetic"),
                        ],
                        db_index=True,
                        default="MAJOR",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "symptoms",
                    models.TextField(help_text="Observed symptoms, free text"),
                ),
                ("symptom_tags", models.JSONField(blank=True, default=list)),
                ("description", models.TextField(blank=True)),
                ("root_cause", models.TextField(blank=True)),
                ("resolution", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("INVESTIGATING", "Investigating"),
                            ("RESOLVED", "Resolved"),
                            ("VERIFIED", "Verified"),
                            ("CLOSED", "Closed"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=24,
                    ),
                ),
                (
                    "is_waiting",
                    models.BooleanField(
                        default=False,
                        help_text="Waiting on parts/person (flag, not a status)",
                    ),
                ),
                ("waiting_reason", models.CharField(blank=True, max_length=255)),
                (
                    "hardware_revision",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "firmware_version",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("parameter_profile", models.CharField(blank=True, max_length=120)),
                (
                    "gcs_version",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "configurator_version",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("is_recurring", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        editable=False, null=True
                    ),
                ),
                (
                    "assigned_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_issues",
                        to="accounts.department",
                    ),
                ),
                (
                    "assigned_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closed_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "discovered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discovered_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "discovered_stage_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discovered_issues",
                        to="fc.stagerecord",
                    ),
                ),
                (
                    "discovering_department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discovered_issues",
                        to="accounts.department",
                    ),
                ),
                (
                    "fc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="fc.flightcontroller",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "root_cause_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="root_cause_issues",
                        to="accounts.department",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="IssueAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="issue-attachments/%Y/%m/")),
                ("original_name", models.CharField(blank=True, max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=120)),
                ("size", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="issues.issue",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issue_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="IssueInvestigationNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="investigation_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investigation_notes",
                        to="issues.issue",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="IssueReassignmentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reassignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reassignments_from",
                        to="accounts.department",
                    ),
                ),
                (
                    "from_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reassignments_from",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reassignments",
                        to="issues.issue",
                    ),
                ),
                (
                    "to_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reassignments_to",
                        to="accounts.department",
                    ),
                ),
                (
                    "to_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reassignments_to",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="KnownIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("symptoms_summary", models.TextField()),
                ("root_cause", models.TextField()),
                ("resolution", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("HARDWARE", "Hardware"),
                            ("FIRMWARE", "Firmware"),
                            ("SOFTWARE", "Software"),
                            ("MECHANICAL", "Mechanical"),
                            ("PROCESS", "Process"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=24,
                    ),
                ),
                ("affected_revisions", models.CharField(blank=True, max_length=255)),
                ("affected_firmware", models.CharField(blank=True, max_length=255)),
                ("affected_software", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("RETIRED", "Retired")],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("verification_count", models.PositiveIntegerField(default=0)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        editable=False, null=True
                    ),
                ),
                (
                    "first_occurrence_issue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="known_issue_first_of",
                        to="issues.issue",
                    ),
                ),
                (
                    "last_occurrence_issue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="known_issue_last_of",
                        to="issues.issue",
                    ),
                ),
                (
                    "owning_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="known_issues",
                        to="accounts.department",
                    ),
                ),
                (
                    "promoted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promoted_known_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
        migrations.AddField(
            model_name="issue",
            name="known_issue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_issues",
                to="issues.knownissue",
            ),
        ),
        migrations.AddIndex(
            model_name="knownissue",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="issues_know_search__7d0322_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="issues_issu_search__5d5ff3_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["status", "severity"], name="issues_issu_status_30204f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["fc", "status"], name="issues_issu_fc_id_bebea9_idx"
            ),
        ),
    ]
