# Generated by Django 5.2.17 on 2026-08-25 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="issueinvestigationnote",
            options={"ordering": ("created_at", "id")},
        ),
        migrations.AlterModelOptions(
            name="issuereassignmentlog",
            options={"ordering": ("created_at", "id")},
        ),
    ]
