# Generated by Django 5.2.17 on 2026-08-25 13:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChecklistTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("FABRICATION", "Fabrication"),
                            ("MANUAL_ASSEMBLY", "Manual Assembly"),
                            ("MACHINE_ASSEMBLY", "Machine Assembly / Soldering"),
                            ("QC", "QC"),
                            ("FIRMWARE", "Firmware"),
                            ("SENSOR_VALIDATION", "Sensor / Functional Validation"),
                            ("MECHANICAL_ASSEMBLY", "Mechanical Assembly"),
                            ("BENCH_TESTING", "Bench Testing"),
                            ("GROUND_TESTING", "Ground Testing"),
                            ("FINAL_VALIDATION", "Final Validation"),
                            ("MANAGER_APPROVAL", "Manager Approval"),
                        ],
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "items",
                    models.JSONField(
                        default=list,
                        help_text='[{"key": "gps_lock", "label": "GPS lock acquired"}]',
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("stage", "name"),
            },
        ),
        migrations.CreateModel(
            name="FCModelType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("code", models.SlugField(max_length=48, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "FC model",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="FirmwareRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("firmware_name", models.CharField(max_length=120)),
                ("version", models.CharField(db_index=True, max_length=64)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("OPEN_SOURCE", "Open source"),
                            ("CLOSED_SOURCE", "Closed source"),
                        ],
                        default="OPEN_SOURCE",
                        max_length=24,
                    ),
                ),
                ("is_signed", models.BooleanField(default=False)),
                ("is_locked", models.BooleanField(default=False)),
                ("bootloader_version", models.CharField(blank=True, max_length=64)),
                (
                    "build_ref",
                    models.CharField(
                        blank=True,
                        help_text="Git SHA / CI build reference",
                        max_length=120,
                    ),
                ),
                ("script_name", models.CharField(blank=True, max_length=120)),
                ("script_version", models.CharField(blank=True, max_length=64)),
                (
                    "flashing_result",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("PARTIAL", "Partial"),
                        ],
                        default="SUCCESS",
                        max_length=16,
                    ),
                ),
                (
                    "config_result",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("PARTIAL", "Partial"),
                        ],
                        default="SUCCESS",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "is_current",
                    models.BooleanField(
                        default=True, help_text="Latest firmware state of this FC"
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="FlightController",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "serial",
                    models.CharField(
                        db_index=True,
                        help_text="FC-YYYY-NNNNN",
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("hardware_revision", models.CharField(blank=True, max_length=64)),
                (
                    "pcb_batch",
                    models.CharField(
                        blank=True,
                        help_text="Fabrication batch / panel reference",
                        max_length=64,
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("FABRICATION", "Fabrication"),
                            ("MANUAL_ASSEMBLY", "Manual Assembly"),
                            ("MACHINE_ASSEMBLY", "Machine Assembly / Soldering"),
                            ("QC", "QC"),
                            ("FIRMWARE", "Firmware"),
                            ("SENSOR_VALIDATION", "Sensor / Functional Validation"),
                            ("MECHANICAL_ASSEMBLY", "Mechanical Assembly"),
                            ("BENCH_TESTING", "Bench Testing"),
                            ("GROUND_TESTING", "Ground Testing"),
                            ("FINAL_VALIDATION", "Final Validation"),
                            ("MANAGER_APPROVAL", "Manager Approval"),
                        ],
                        db_index=True,
                        default="FABRICATION",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PRODUCTION", "In production"),
                            ("BLOCKED", "Blocked"),
                            ("IN_TESTING", "In testing"),
                            ("PENDING_APPROVAL", "Pending approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected / scrapped"),
                        ],
                        db_index=True,
                        default="IN_PRODUCTION",
                        max_length=24,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approval_note", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ParameterProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("version", models.CharField(max_length=48)),
                (
                    "contents_ref",
                    models.CharField(
                        blank=True,
                        help_text="Path/URL/git ref to the param file",
                        max_length=255,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("name", "version"),
            },
        ),
        migrations.CreateModel(
            name="ReworkRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField()),
                (
                    "return_to_stage",
                    models.CharField(
                        choices=[
                            ("FABRICATION", "Fabrication"),
                            ("MANUAL_ASSEMBLY", "Manual Assembly"),
                            ("MACHINE_ASSEMBLY", "Machine Assembly / Soldering"),
                            ("QC", "QC"),
                            ("FIRMWARE", "Firmware"),
                            ("SENSOR_VALIDATION", "Sensor / Functional Validation"),
                            ("MECHANICAL_ASSEMBLY", "Mechanical Assembly"),
                            ("BENCH_TESTING", "Bench Testing"),
                            ("GROUND_TESTING", "Ground Testing"),
                            ("FINAL_VALIDATION", "Final Validation"),
                            ("MANAGER_APPROVAL", "Manager Approval"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("outcome_notes", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="SoftwareVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("GCS", "GCS"), ("CONFIGURATOR", "Configurator")],
                        max_length=24,
                    ),
                ),
                ("version", models.CharField(max_length=64)),
                ("released_on", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("kind", "-version"),
            },
        ),
        migrations.CreateModel(
            name="StageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("FABRICATION", "Fabrication"),
                            ("MANUAL_ASSEMBLY", "Manual Assembly"),
                            ("MACHINE_ASSEMBLY", "Machine Assembly / Soldering"),
                            ("QC", "QC"),
                            ("FIRMWARE", "Firmware"),
                            ("SENSOR_VALIDATION", "Sensor / Functional Validation"),
                            ("MECHANICAL_ASSEMBLY", "Mechanical Assembly"),
                            ("BENCH_TESTING", "Bench Testing"),
                            ("GROUND_TESTING", "Ground Testing"),
                            ("FINAL_VALIDATION", "Final Validation"),
                            ("MANAGER_APPROVAL", "Manager Approval"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("attempt", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In progress"),
                            ("PASSED", "Passed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("fc_id", "id"),
            },
        ),
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("FABRICATION", "Fabrication"),
                            ("MANUAL_ASSEMBLY", "Manual Assembly"),
                            ("MACHINE_ASSEMBLY", "Machine Assembly / Soldering"),
                            ("QC", "QC"),
                            ("FIRMWARE", "Firmware"),
                            ("SENSOR_VALIDATION", "Sensor / Functional Validation"),
                            ("MECHANICAL_ASSEMBLY", "Mechanical Assembly"),
                            ("BENCH_TESTING", "Bench Testing"),
                            ("GROUND_TESTING", "Ground Testing"),
                            ("FINAL_VALIDATION", "Final Validation"),
                            ("MANAGER_APPROVAL", "Manager Approval"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "checklist_results",
                    models.JSONField(
                        default=list,
                        help_text='[{"key":"gps_lock","label":"GPS lock","passed":false,"note":"no fix"}]',
                    ),
                ),
                ("overall_passed", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="FCEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(db_index=True, max_length=48)),
                ("title", models.CharField(max_length=255)),
                ("detail", models.TextField(blank=True)),
                ("stage", models.CharField(blank=True, max_length=32)),
                ("payload", models.JSONField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fc_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
    ]
