# Generated by Django 5.2.17 on 2026-08-25 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fc", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="checklisttemplate",
            name="version",
            field=models.PositiveIntegerField(
                default=1, help_text="Bumped whenever the item set changes."
            ),
        ),
        migrations.AddField(
            model_name="testresult",
            name="template_version",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Template version answered, so a later edit cannot be mistaken for what this tester actually saw.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="checklisttemplate",
            name="items",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Legacy inline items. Superseded by ChecklistItem rows; kept so historical templates remain readable.",
            ),
        ),
        migrations.CreateModel(
            name="FirmwareBuild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "firmware_type",
                    models.CharField(
                        default="APJ",
                        help_text="Build format, e.g. APJ. Free text so new formats need no schema change.",
                        max_length=32,
                    ),
                ),
                ("version", models.CharField(db_index=True, max_length=64)),
                (
                    "git_sha",
                    models.CharField(
                        blank=True,
                        help_text="Source reference for this build",
                        max_length=120,
                    ),
                ),
                ("build_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("OPEN_SOURCE", "Open source"),
                            ("CLOSED_SOURCE", "Closed source"),
                        ],
                        default="OPEN_SOURCE",
                        max_length=24,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="What this build contains, changes and enables",
                    ),
                ),
                ("includes_scripts", models.BooleanField(default=False)),
                ("script_name", models.CharField(blank=True, max_length=120)),
                ("script_version", models.CharField(blank=True, max_length=64)),
                ("script_notes", models.TextField(blank=True)),
                ("is_signed", models.BooleanField(default=False)),
                ("is_locked", models.BooleanField(default=False)),
                ("bootloader_version", models.CharField(blank=True, max_length=64)),
                ("bootloader_notes", models.TextField(blank=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive builds cannot be selected for new flashes but remain in FC history",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="firmware_builds_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fc_models",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Empty = suitable for any model",
                        related_name="firmware_builds",
                        to="fc.fcmodeltype",
                    ),
                ),
                (
                    "parameter_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="firmware_builds",
                        to="fc.parameterprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "unique_together": {("name", "version")},
            },
        ),
        migrations.AddField(
            model_name="firmwarerecord",
            name="build",
            field=models.ForeignKey(
                blank=True,
                help_text="Catalogue build this flash came from. PROTECT: a build that has been flashed can never be deleted.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="flashes",
                to="fc.firmwarebuild",
            ),
        ),
        migrations.CreateModel(
            name="ChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Stable identifier stored in test results",
                        max_length=64,
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Instructions shown to the tester"
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=True,
                        help_text="A mandatory check must pass for the test to pass",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_items",
                        to="fc.checklisttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "unique_together": {("template", "key")},
            },
        ),
        migrations.CreateModel(
            name="SoftwareUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("GCS", "GCS"), ("CONFIGURATOR", "Configurator")],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                ("version", models.CharField(db_index=True, max_length=64)),
                (
                    "git_sha",
                    models.CharField(
                        help_text="Commit that produced this build (required)",
                        max_length=120,
                    ),
                ),
                (
                    "release_notes",
                    models.TextField(help_text="What changed in this update"),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_software_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pushed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pushed_software_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "software_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updates",
                        to="fc.softwareversion",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "unique_together": {("kind", "version")},
            },
        ),
    ]
